"""add id_in_browser to customer table

Revision ID: 56a632d538c2
Revises: 87b47891983f
Create Date: 2026-09-30 17:40:30.289083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a632d538c2'
down_revision: Union[str, Sequence[str], None] = '87b47891983f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('id_in_browser', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'id_in_browser')
    # ### end Alembic commands ###
