"""add due_date and id_in_browser to entries table

Revision ID: 70a070190f5a
Revises: cf7ec2cc0934
Create Date: 2026-10-10 13:49:16.073052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a070190f5a'
down_revision: Union[str, Sequence[str], None] = 'cf7ec2cc0934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entries', sa.Column('id_in_browser', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'id_in_browser')
    op.drop_column('entries', 'due_date')
    # ### end Alembic commands ###
