"""add id_in_browser to item schema and increase limit for phone_number for customer

Revision ID: 8368729ec16e
Revises: ba15831077f3
Create Date: 2026-10-05 16:50:13.648616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8368729ec16e'
down_revision: Union[str, Sequence[str], None] = 'ba15831077f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_number',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.add_column('items', sa.Column('id_in_browser', sa.BigInteger(), nullable=True))
    op.drop_constraint(op.f('items_name_key'), 'items', type_='unique')
    op.create_unique_constraint('uq_business_item_name', 'items', ['business_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_item_name', 'items', type_='unique')
    op.create_unique_constraint(op.f('items_name_key'), 'items', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('items', 'id_in_browser')
    op.alter_column('customers', 'phone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
