"""Add business_id to customer unique constraint

Revision ID: ba15831077f3
Revises: 56a632d538c2
Create Date: 2026-09-30 18:56:18.120611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba15831077f3'
down_revision: Union[str, Sequence[str], None] = '56a632d538c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customers_name_key'), 'customers', type_='unique')
    op.drop_constraint(op.f('customers_phone_number_key'), 'customers', type_='unique')
    op.create_unique_constraint('uq_business_customer_name', 'customers', ['business_id', 'name'])
    op.create_unique_constraint('uq_business_customer_phone', 'customers', ['business_id', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_customer_phone', 'customers', type_='unique')
    op.drop_constraint('uq_business_customer_name', 'customers', type_='unique')
    op.create_unique_constraint(op.f('customers_phone_number_key'), 'customers', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customers_name_key'), 'customers', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
