"""add entryitem schema

Revision ID: cf7ec2cc0934
Revises: 8368729ec16e
Create Date: 2026-10-10 13:04:47.084076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7ec2cc0934'
down_revision: Union[str, Sequence[str], None] = '8368729ec16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('wash', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('iron', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('starch', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_items_entry_id'), 'entry_items', ['entry_id'], unique=False)
    op.create_index(op.f('ix_entry_items_item_id'), 'entry_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_items_item_id'), table_name='entry_items')
    op.drop_index(op.f('ix_entry_items_entry_id'), table_name='entry_items')
    op.drop_table('entry_items')
    # ### end Alembic commands ###
