"""add role to user schema

Revision ID: e7d8cd40ecc8
Revises: 0448f3238690
Create Date: 2026-09-04 06:27:31.860030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d8cd40ecc8'
down_revision: Union[str, Sequence[str], None] = '0448f3238690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='userrole', native_enum=False), server_default='staff', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
